spring:
  thymeleaf:
    cache: false
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/novel?serverTimezone=UTC
      username: root
      password: lhfadmin
      db-type: mysql
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: com/lhf/springsecurity/dao/mysql/*.xml
